### ISSUE TITLE
Incomplete dataset file (GoodReads)

### ISSUE THREAD

**Issue by Ginphy** [Hope-Rita/THLM#1]
Hello, the file for the GoodReads dataset in the download link (DatasetsForTHLM) you provided is incomplete. The GoodReads dataset is missing the 'abstract.csv' file, which is required in the '/config/GoodReads.json' file. Could you please provide the complete file? Thank you~

**Comment by Hope-Rita** [comment]
We apologize for the incomplete data files. We have now updated the 'abstract.csv' file in the download link. Kindly download the file from the original link provided.
